/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed-variant": "#6f3800",
        "surface-container-highest": "#d9e3f6",
        "surface-container": "#e6eeff",
        "secondary-fixed": "#dae4e4",
        "tertiary-container": "#804307",
        "surface-dim": "#d0dbed",
        "tertiary-fixed": "#ffdcc4",
        "primary-fixed": "#acefe3",
        "inverse-primary": "#90d3c7",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#90d3c7",
        "on-primary-container": "#91d3c8",
        "surface-container-low": "#eff4ff",
        "background": "#f8f9ff",
        "on-tertiary-fixed": "#2f1400",
        "secondary-fixed-dim": "#bec8c8",
        "on-secondary-fixed-variant": "#3f4948",
        "surface-container-high": "#dee9fc",
        "outline-variant": "#bfc9c5",
        "primary": "#00443d",
        "primary-container": "#135d54",
        "on-primary": "#ffffff",
        "on-surface-variant": "#3f4946",
        "on-secondary": "#ffffff",
        "tertiary": "#5f2f00",
        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "on-surface": "#121c2a",
        "tertiary-fixed-dim": "#ffb780",
        "on-tertiary": "#ffffff",
        "on-background": "#121c2a",
        "on-secondary-fixed": "#141d1d",
        "on-primary-fixed-variant": "#005048",
        "on-tertiary-container": "#ffb882",
        "error-container": "#ffdad6",
        "surface-variant": "#d9e3f6",
        "secondary": "#576060",
        "outline": "#6f7977",
        "error": "#ba1a1a",
        "on-primary-fixed": "#00201c",
        "on-secondary-container": "#5c6666",
        "secondary-container": "#dae4e4",
        "inverse-surface": "#27313f",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#23695f",
        "surface-container-lowest": "#ffffff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "4px",
        "container-margin": "24px",
        "sm": "12px",
        "xs": "8px",
        "xl": "32px",
        "md": "16px",
        "lg": "24px",
        "gutter": "16px"
      },
      "fontFamily": {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"]
      },
      "fontSize": {
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-sm": ["18px", {"lineHeight": "26px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
